# coding: utf-8

"""
    4CS GPS Tracking System

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 4.8
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import TraccarClient
from TraccarClient.models.geofence import Geofence  # noqa: E501
from TraccarClient.rest import ApiException


class TestGeofence(unittest.TestCase):
    """Geofence unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGeofence(self):
        """Test Geofence"""
        # FIXME: construct object with mandatory attributes with example values
        # model = TraccarClient.models.geofence.Geofence()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
