# coding: utf-8

"""
    4CS GPS Tracking System

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 4.8
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import TraccarClient
from TraccarClient.models.notification_type import NotificationType  # noqa: E501
from TraccarClient.rest import ApiException


class TestNotificationType(unittest.TestCase):
    """NotificationType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNotificationType(self):
        """Test NotificationType"""
        # FIXME: construct object with mandatory attributes with example values
        # model = TraccarClient.models.notification_type.NotificationType()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
