# coding: utf-8

"""
    4CS GPS Tracking System

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 4.8
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import TraccarClient
from TraccarClient.models.maintenance import Maintenance  # noqa: E501
from TraccarClient.rest import ApiException


class TestMaintenance(unittest.TestCase):
    """Maintenance unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMaintenance(self):
        """Test Maintenance"""
        # FIXME: construct object with mandatory attributes with example values
        # model = TraccarClient.models.maintenance.Maintenance()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
