# coding: utf-8

"""
    4CS GPS Tracking System

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 4.8
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class Event(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'int',
        'type': 'str',
        'server_time': 'datetime',
        'device_id': 'int',
        'position_id': 'int',
        'geofence_id': 'int',
        'maintenance_id': 'int',
        'attributes': 'dict(str, object)'
    }

    attribute_map = {
        'id': 'id',
        'type': 'type',
        'server_time': 'serverTime',
        'device_id': 'deviceId',
        'position_id': 'positionId',
        'geofence_id': 'geofenceId',
        'maintenance_id': 'maintenanceId',
        'attributes': 'attributes'
    }

    def __init__(self, id=None, type=None, server_time=None, device_id=None, position_id=None, geofence_id=None, maintenance_id=None, attributes=None):  # noqa: E501
        """Event - a model defined in Swagger"""  # noqa: E501

        self._id = None
        self._type = None
        self._server_time = None
        self._device_id = None
        self._position_id = None
        self._geofence_id = None
        self._maintenance_id = None
        self._attributes = None
        self.discriminator = None

        if id is not None:
            self.id = id
        if type is not None:
            self.type = type
        if server_time is not None:
            self.server_time = server_time
        if device_id is not None:
            self.device_id = device_id
        if position_id is not None:
            self.position_id = position_id
        if geofence_id is not None:
            self.geofence_id = geofence_id
        if maintenance_id is not None:
            self.maintenance_id = maintenance_id
        if attributes is not None:
            self.attributes = attributes

    @property
    def id(self):
        """Gets the id of this Event.  # noqa: E501


        :return: The id of this Event.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this Event.


        :param id: The id of this Event.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def type(self):
        """Gets the type of this Event.  # noqa: E501


        :return: The type of this Event.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this Event.


        :param type: The type of this Event.  # noqa: E501
        :type: str
        """

        self._type = type

    @property
    def server_time(self):
        """Gets the server_time of this Event.  # noqa: E501

        in IS0 8601 format. eg. `1963-11-22T18:30:00Z`  # noqa: E501

        :return: The server_time of this Event.  # noqa: E501
        :rtype: datetime
        """
        return self._server_time

    @server_time.setter
    def server_time(self, server_time):
        """Sets the server_time of this Event.

        in IS0 8601 format. eg. `1963-11-22T18:30:00Z`  # noqa: E501

        :param server_time: The server_time of this Event.  # noqa: E501
        :type: datetime
        """

        self._server_time = server_time

    @property
    def device_id(self):
        """Gets the device_id of this Event.  # noqa: E501


        :return: The device_id of this Event.  # noqa: E501
        :rtype: int
        """
        return self._device_id

    @device_id.setter
    def device_id(self, device_id):
        """Sets the device_id of this Event.


        :param device_id: The device_id of this Event.  # noqa: E501
        :type: int
        """

        self._device_id = device_id

    @property
    def position_id(self):
        """Gets the position_id of this Event.  # noqa: E501


        :return: The position_id of this Event.  # noqa: E501
        :rtype: int
        """
        return self._position_id

    @position_id.setter
    def position_id(self, position_id):
        """Sets the position_id of this Event.


        :param position_id: The position_id of this Event.  # noqa: E501
        :type: int
        """

        self._position_id = position_id

    @property
    def geofence_id(self):
        """Gets the geofence_id of this Event.  # noqa: E501


        :return: The geofence_id of this Event.  # noqa: E501
        :rtype: int
        """
        return self._geofence_id

    @geofence_id.setter
    def geofence_id(self, geofence_id):
        """Sets the geofence_id of this Event.


        :param geofence_id: The geofence_id of this Event.  # noqa: E501
        :type: int
        """

        self._geofence_id = geofence_id

    @property
    def maintenance_id(self):
        """Gets the maintenance_id of this Event.  # noqa: E501


        :return: The maintenance_id of this Event.  # noqa: E501
        :rtype: int
        """
        return self._maintenance_id

    @maintenance_id.setter
    def maintenance_id(self, maintenance_id):
        """Sets the maintenance_id of this Event.


        :param maintenance_id: The maintenance_id of this Event.  # noqa: E501
        :type: int
        """

        self._maintenance_id = maintenance_id

    @property
    def attributes(self):
        """Gets the attributes of this Event.  # noqa: E501


        :return: The attributes of this Event.  # noqa: E501
        :rtype: dict(str, object)
        """
        return self._attributes

    @attributes.setter
    def attributes(self, attributes):
        """Sets the attributes of this Event.


        :param attributes: The attributes of this Event.  # noqa: E501
        :type: dict(str, object)
        """

        self._attributes = attributes

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Event, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Event):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
