# coding: utf-8

"""
    4CS GPS Tracking System

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 4.8
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class User(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'int',
        'name': 'str',
        'email': 'str',
        'readonly': 'bool',
        'administrator': 'bool',
        'map': 'str',
        'latitude': 'float',
        'longitude': 'float',
        'zoom': 'int',
        'password': 'str',
        'twelve_hour_format': 'bool',
        'coordinate_format': 'str',
        'disabled': 'bool',
        'expiration_time': 'datetime',
        'device_limit': 'int',
        'user_limit': 'int',
        'device_readonly': 'bool',
        'limit_commands': 'bool',
        'poi_layer': 'str',
        'token': 'str',
        'attributes': 'dict(str, object)'
    }

    attribute_map = {
        'id': 'id',
        'name': 'name',
        'email': 'email',
        'readonly': 'readonly',
        'administrator': 'administrator',
        'map': 'map',
        'latitude': 'latitude',
        'longitude': 'longitude',
        'zoom': 'zoom',
        'password': 'password',
        'twelve_hour_format': 'twelveHourFormat',
        'coordinate_format': 'coordinateFormat',
        'disabled': 'disabled',
        'expiration_time': 'expirationTime',
        'device_limit': 'deviceLimit',
        'user_limit': 'userLimit',
        'device_readonly': 'deviceReadonly',
        'limit_commands': 'limitCommands',
        'poi_layer': 'poiLayer',
        'token': 'token',
        'attributes': 'attributes'
    }

    def __init__(self, id=None, name=None, email=None, readonly=None, administrator=None, map=None, latitude=None, longitude=None, zoom=None, password=None, twelve_hour_format=None, coordinate_format=None, disabled=None, expiration_time=None, device_limit=None, user_limit=None, device_readonly=None, limit_commands=None, poi_layer=None, token=None, attributes=None):  # noqa: E501
        """User - a model defined in Swagger"""  # noqa: E501

        self._id = None
        self._name = None
        self._email = None
        self._readonly = None
        self._administrator = None
        self._map = None
        self._latitude = None
        self._longitude = None
        self._zoom = None
        self._password = None
        self._twelve_hour_format = None
        self._coordinate_format = None
        self._disabled = None
        self._expiration_time = None
        self._device_limit = None
        self._user_limit = None
        self._device_readonly = None
        self._limit_commands = None
        self._poi_layer = None
        self._token = None
        self._attributes = None
        self.discriminator = None

        if id is not None:
            self.id = id
        if name is not None:
            self.name = name
        if email is not None:
            self.email = email
        if readonly is not None:
            self.readonly = readonly
        if administrator is not None:
            self.administrator = administrator
        if map is not None:
            self.map = map
        if latitude is not None:
            self.latitude = latitude
        if longitude is not None:
            self.longitude = longitude
        if zoom is not None:
            self.zoom = zoom
        if password is not None:
            self.password = password
        if twelve_hour_format is not None:
            self.twelve_hour_format = twelve_hour_format
        if coordinate_format is not None:
            self.coordinate_format = coordinate_format
        if disabled is not None:
            self.disabled = disabled
        if expiration_time is not None:
            self.expiration_time = expiration_time
        if device_limit is not None:
            self.device_limit = device_limit
        if user_limit is not None:
            self.user_limit = user_limit
        if device_readonly is not None:
            self.device_readonly = device_readonly
        if limit_commands is not None:
            self.limit_commands = limit_commands
        if poi_layer is not None:
            self.poi_layer = poi_layer
        if token is not None:
            self.token = token
        if attributes is not None:
            self.attributes = attributes

    @property
    def id(self):
        """Gets the id of this User.  # noqa: E501


        :return: The id of this User.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this User.


        :param id: The id of this User.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def name(self):
        """Gets the name of this User.  # noqa: E501


        :return: The name of this User.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this User.


        :param name: The name of this User.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def email(self):
        """Gets the email of this User.  # noqa: E501


        :return: The email of this User.  # noqa: E501
        :rtype: str
        """
        return self._email

    @email.setter
    def email(self, email):
        """Sets the email of this User.


        :param email: The email of this User.  # noqa: E501
        :type: str
        """

        self._email = email

    @property
    def readonly(self):
        """Gets the readonly of this User.  # noqa: E501


        :return: The readonly of this User.  # noqa: E501
        :rtype: bool
        """
        return self._readonly

    @readonly.setter
    def readonly(self, readonly):
        """Sets the readonly of this User.


        :param readonly: The readonly of this User.  # noqa: E501
        :type: bool
        """

        self._readonly = readonly

    @property
    def administrator(self):
        """Gets the administrator of this User.  # noqa: E501


        :return: The administrator of this User.  # noqa: E501
        :rtype: bool
        """
        return self._administrator

    @administrator.setter
    def administrator(self, administrator):
        """Sets the administrator of this User.


        :param administrator: The administrator of this User.  # noqa: E501
        :type: bool
        """

        self._administrator = administrator

    @property
    def map(self):
        """Gets the map of this User.  # noqa: E501


        :return: The map of this User.  # noqa: E501
        :rtype: str
        """
        return self._map

    @map.setter
    def map(self, map):
        """Sets the map of this User.


        :param map: The map of this User.  # noqa: E501
        :type: str
        """

        self._map = map

    @property
    def latitude(self):
        """Gets the latitude of this User.  # noqa: E501


        :return: The latitude of this User.  # noqa: E501
        :rtype: float
        """
        return self._latitude

    @latitude.setter
    def latitude(self, latitude):
        """Sets the latitude of this User.


        :param latitude: The latitude of this User.  # noqa: E501
        :type: float
        """

        self._latitude = latitude

    @property
    def longitude(self):
        """Gets the longitude of this User.  # noqa: E501


        :return: The longitude of this User.  # noqa: E501
        :rtype: float
        """
        return self._longitude

    @longitude.setter
    def longitude(self, longitude):
        """Sets the longitude of this User.


        :param longitude: The longitude of this User.  # noqa: E501
        :type: float
        """

        self._longitude = longitude

    @property
    def zoom(self):
        """Gets the zoom of this User.  # noqa: E501


        :return: The zoom of this User.  # noqa: E501
        :rtype: int
        """
        return self._zoom

    @zoom.setter
    def zoom(self, zoom):
        """Sets the zoom of this User.


        :param zoom: The zoom of this User.  # noqa: E501
        :type: int
        """

        self._zoom = zoom

    @property
    def password(self):
        """Gets the password of this User.  # noqa: E501


        :return: The password of this User.  # noqa: E501
        :rtype: str
        """
        return self._password

    @password.setter
    def password(self, password):
        """Sets the password of this User.


        :param password: The password of this User.  # noqa: E501
        :type: str
        """

        self._password = password

    @property
    def twelve_hour_format(self):
        """Gets the twelve_hour_format of this User.  # noqa: E501


        :return: The twelve_hour_format of this User.  # noqa: E501
        :rtype: bool
        """
        return self._twelve_hour_format

    @twelve_hour_format.setter
    def twelve_hour_format(self, twelve_hour_format):
        """Sets the twelve_hour_format of this User.


        :param twelve_hour_format: The twelve_hour_format of this User.  # noqa: E501
        :type: bool
        """

        self._twelve_hour_format = twelve_hour_format

    @property
    def coordinate_format(self):
        """Gets the coordinate_format of this User.  # noqa: E501


        :return: The coordinate_format of this User.  # noqa: E501
        :rtype: str
        """
        return self._coordinate_format

    @coordinate_format.setter
    def coordinate_format(self, coordinate_format):
        """Sets the coordinate_format of this User.


        :param coordinate_format: The coordinate_format of this User.  # noqa: E501
        :type: str
        """

        self._coordinate_format = coordinate_format

    @property
    def disabled(self):
        """Gets the disabled of this User.  # noqa: E501


        :return: The disabled of this User.  # noqa: E501
        :rtype: bool
        """
        return self._disabled

    @disabled.setter
    def disabled(self, disabled):
        """Sets the disabled of this User.


        :param disabled: The disabled of this User.  # noqa: E501
        :type: bool
        """

        self._disabled = disabled

    @property
    def expiration_time(self):
        """Gets the expiration_time of this User.  # noqa: E501

        in IS0 8601 format. eg. `1963-11-22T18:30:00Z`  # noqa: E501

        :return: The expiration_time of this User.  # noqa: E501
        :rtype: datetime
        """
        return self._expiration_time

    @expiration_time.setter
    def expiration_time(self, expiration_time):
        """Sets the expiration_time of this User.

        in IS0 8601 format. eg. `1963-11-22T18:30:00Z`  # noqa: E501

        :param expiration_time: The expiration_time of this User.  # noqa: E501
        :type: datetime
        """

        self._expiration_time = expiration_time

    @property
    def device_limit(self):
        """Gets the device_limit of this User.  # noqa: E501


        :return: The device_limit of this User.  # noqa: E501
        :rtype: int
        """
        return self._device_limit

    @device_limit.setter
    def device_limit(self, device_limit):
        """Sets the device_limit of this User.


        :param device_limit: The device_limit of this User.  # noqa: E501
        :type: int
        """

        self._device_limit = device_limit

    @property
    def user_limit(self):
        """Gets the user_limit of this User.  # noqa: E501


        :return: The user_limit of this User.  # noqa: E501
        :rtype: int
        """
        return self._user_limit

    @user_limit.setter
    def user_limit(self, user_limit):
        """Sets the user_limit of this User.


        :param user_limit: The user_limit of this User.  # noqa: E501
        :type: int
        """

        self._user_limit = user_limit

    @property
    def device_readonly(self):
        """Gets the device_readonly of this User.  # noqa: E501


        :return: The device_readonly of this User.  # noqa: E501
        :rtype: bool
        """
        return self._device_readonly

    @device_readonly.setter
    def device_readonly(self, device_readonly):
        """Sets the device_readonly of this User.


        :param device_readonly: The device_readonly of this User.  # noqa: E501
        :type: bool
        """

        self._device_readonly = device_readonly

    @property
    def limit_commands(self):
        """Gets the limit_commands of this User.  # noqa: E501


        :return: The limit_commands of this User.  # noqa: E501
        :rtype: bool
        """
        return self._limit_commands

    @limit_commands.setter
    def limit_commands(self, limit_commands):
        """Sets the limit_commands of this User.


        :param limit_commands: The limit_commands of this User.  # noqa: E501
        :type: bool
        """

        self._limit_commands = limit_commands

    @property
    def poi_layer(self):
        """Gets the poi_layer of this User.  # noqa: E501


        :return: The poi_layer of this User.  # noqa: E501
        :rtype: str
        """
        return self._poi_layer

    @poi_layer.setter
    def poi_layer(self, poi_layer):
        """Sets the poi_layer of this User.


        :param poi_layer: The poi_layer of this User.  # noqa: E501
        :type: str
        """

        self._poi_layer = poi_layer

    @property
    def token(self):
        """Gets the token of this User.  # noqa: E501


        :return: The token of this User.  # noqa: E501
        :rtype: str
        """
        return self._token

    @token.setter
    def token(self, token):
        """Sets the token of this User.


        :param token: The token of this User.  # noqa: E501
        :type: str
        """

        self._token = token

    @property
    def attributes(self):
        """Gets the attributes of this User.  # noqa: E501


        :return: The attributes of this User.  # noqa: E501
        :rtype: dict(str, object)
        """
        return self._attributes

    @attributes.setter
    def attributes(self, attributes):
        """Sets the attributes of this User.


        :param attributes: The attributes of this User.  # noqa: E501
        :type: dict(str, object)
        """

        self._attributes = attributes

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(User, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, User):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
